### ISSUE TITLE
hydration error

### ISSUE THREAD

**Issue by krishmarsonia** [krishmarsonia/js-time#1]
A hydration error is coming from seconds input field when a page is refreshed. The error stats that "Text content does not match server-rendered HTML.".
![image](https://github.com/krishmarsonia/js-time/assets/69512823/42977779-08af-41cd-9263-25732a99a924)

**Comment by vimalsonara** [comment]
fix in 15500f518b00cba60423da0564e3057d4548fcf1

**Comment by vimalsonara** [comment]
Fix by adding isMount state return null if component not mounted
